### ISSUE TITLE
[BUG] Скачивание некорректных данных ломает сторис

### ISSUE THREAD

**Issue by L3odr0id** [Ninja-Official/rtu-mirea-mobile#114]
**Описание ошибки**
Одна из скачанных сторис имеет некорректные данные, что приводит к поломке всего блока сторис. Предположительно, отсутствуют словари `large`, `medium`, `small` внутри ноды `formats`

**Воспроизведение ошибки**
Шаги воспроизведения:
1. Открыть приложение
2. Перейти на страницу новостей

**Ожидаемое поведение**
История с битыми данными может не отображаться, но корретные должны быть обработаны и показаны пользователю

**Скриншоты**
Скриншот полученных данных:
![image](https://user-images.githubusercontent.com/62698748/143735508-7d8c9325-a855-4772-89c8-c125df66eba1.png)

Устройство:
![image](https://user-images.githubusercontent.com/62698748/143735587-cf0588cf-37ef-4bfd-9302-0971f927ce49.png)

**Смартфон (пожалуйста, заполните следующую информацию):**
 - Девайс: Эмулятор Ipod Touch 7th generation
 - OS: IOS 14.5
 - Версия: Актуальная сборка из dev ветки (в pubspec указана 1.0.1+3)

**Дополнительно**
Стоит установить проверки на null или хотя бы try-catch на этапах парсинга данных, чтобы в результате опечаток не падало всё остальное

**Полный лог ошибки**
```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Unhandled error type 'Null' is not a subtype of type 'Map<String, dynamic>' occurred in Instance of 'StoriesBloc'.
#0      new FormatsModel.fromJson
package:rtu_mirea_app/…/models/strapi_media_model.dart:64
#1      new StrapiMediaModel.fromJson
package:rtu_mirea_app/…/models/strapi_media_model.dart:33
#2      new AuthorModel.fromJson
package:rtu_mirea_app/…/models/story_model.dart:94
#3      new StoryModel.fromJson
package:rtu_mirea_app/…/models/story_model.dart:24
#4      StrapiRemoteDataImpl.getStories.<anonymous closure>
package:rtu_mirea_app/…/datasources/strapi_remote.dart:23
#5      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#6      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#7      new List.from (dart:core-patch/array_patch.dart:40:17)
#8      StrapiRemoteDataImpl.getStories
package:rtu_mirea_app/…/datasources/strapi_remote.dart:22
<asynchronous suspen<…>

```

**Comment by L3odr0id** [comment]
Проблема решена в [этом](https://github.com/Ninja-Official/rtu-mirea-mobile/commit/0d3658441788a7dfc2f633463dccb78320275dce) коммите
